[build]
builder = "DOCKERFILE"
dockerfile_path = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/health"
healthcheckTimeout = 5

[[service]]
name = "backend"
root = "/"
