[build]
builder = "DOCKERFILE"
dockerfile_path = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 30

[[service]]
name = "backend"
root = "/"
